# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/v1/openapi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61se/v1/openapi.proto\x12\x07\x62\x61se.v1\x1a.protoc-gen-openapiv2/options/annotations.protoB\x9c\x03Z)github.com/Permify/permify/pkg/pb/base/v1\x92\x41\xed\x02\x12\x9e\x02\n\x0bPermify API\x12mPermify is an open source authorization service for creating fine-grained and scalable authorization systems.\"J\n\x0b\x41PI Support\x12)https://github.com/Permify/permify/issues\x1a\x10hello@permify.co*L\n\x12\x41pache-2.0 license\x12\x36https://github.com/Permify/permify/blob/master/LICENSE2\x06v0.8.0*\x01\x02\x32\x10\x61pplication/json:\x10\x61pplication/jsonZ#\n!\n\nApiKeyAuth\x12\x13\x08\x02\x1a\rAuthorization \x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base.v1.openapi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/Permify/permify/pkg/pb/base/v1\222A\355\002\022\236\002\n\013Permify API\022mPermify is an open source authorization service for creating fine-grained and scalable authorization systems.\"J\n\013API Support\022)https://github.com/Permify/permify/issues\032\020hello@permify.co*L\n\022Apache-2.0 license\0226https://github.com/Permify/permify/blob/master/LICENSE2\006v0.8.0*\001\0022\020application/json:\020application/jsonZ#\n!\n\nApiKeyAuth\022\023\010\002\032\rAuthorization \002'
# @@protoc_insertion_point(module_scope)
